name: koesie10-t2
main: com.tenjava.entries.koesie10.t2.TenJava
version: '${project.version}'
author: koesie10
commands:
   minigames:
      description: Main command for koesie10-t2
      usage: /<command>
      aliases: [mg, game, ctf]
permissions:
    minigames.*:
        description: Gives access to all koesie10-t2 commands
        children:
            minigames.info: true
            minigames.start: true
    minigames.info:
        description: Allows you to view the info of a gamemode
        default: true
    minigames.start:
        description: Allows you to start a new gamemode
        default: op