name: koesie10-t2
main: com.tenjava.entries.koesie10.t2.TenJava
version: '${project.version}'
author: koesie10
commands:
   murder:
      description: Main command for koesie10-t2
      usage: /<command>
      aliases: [m]
permissions:
    murder.*:
        description: Gives access to all koesie10-t2 commands
        children:
            minigames.start: true
    murder.start:
        description: Allows you to start a new game
        default: op